vars:
  stage: staging
  region: ca-central-1
# Import the component default configurations
import:
- defaults/vpc-flow-logs-bucket
- defaults/vpc

components:
  terraform:
    # Customize the `vpc` component for the `staging` account
    # You can define variables or override the imported defaults
    vpc:
      vars:
        map_public_ip_on_launch: false
        vpc_flow_logs_traffic_type: "REJECT"
