[run_docker]
volumes = [
    "$env:USERPROFILE:/localhost",
    "C:\\DHE\\git\\nls-infra\\root_git\\atmos\\AWS:/_repotest",
]

[docker_manager]
docker_file = 'dockerfile'
image_name = 'geodesic-test-2024-01-25'
