ARG VERSION=2.0.0
ARG OS=debian
FROM cloudposse/geodesic:latest-debian
# FROM cloudposse/geodesic:$VERSION-$OS

# Install prerequisites
RUN apt-get update
RUN apt-get install -y wget

# System: Set TimeZone
RUN sudo ln -sf /usr/share/zoneinfo/America/Denver /etc/localtime


# ---- Set Versions
# https://go.dev/dl/
ARG GO_VERSION=1.21.6

# https://github.com/cloudposse/atmos/releases
ARG ATMOS_VERSION=v1.56.1

# ---- Install Go
# Install Go
RUN wget https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
RUN rm go${GO_VERSION}.linux-amd64.tar.gz

# Set environment variables
ENV GOROOT /usr/local/go
ENV GOPATH /root/go
ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH

# ---- Install Atmos

RUN go install github.com/cloudposse/atmos@${ATMOS_VERSION}

RUN go install github.com/gofireflyio/aiac/v4@latest

# Install Atmos completion commands
RUN atmos completion bash


# Step 1: Set a custom BANNER by changing the value of ENV BANNER in the Dockerfile.
ARG BANNER
ENV BANNER=${BANNER:-"DHE-Geodesic"}

# Step 2: Set the initial AWS_PROFILE by adding a new line: ENV AWS_PROFILE="your-profile"
ARG AWS_PROFILE
ENV AWS_PROFILE=${AWS_PROFILE:-"default-profile"}

# Step 3: Set the AWS_DEFAULT_REGION by adding a new line: ENV AWS_DEFAULT_REGION="your-region"
ARG AWS_DEFAULT_REGION
ENV AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-"default-region"}
